### ISSUE TITLE
Error with the build of Singularity.busco-4.0.4.def

### ISSUE THREAD

**Issue by X-Mialhe** [SouthGreenPlatform/culebrONT#1]
Hi,

I tried to build Singularity.busco-4.0.4.def with `singularity build busco-4.0.4 Singularity.busco-4.0.4.def` and I get an error 
[busco_brut.log](https://github.com/SouthGreenPlatform/CulebrONT_pipeline/files/5835914/busco_brut.log)

I changed ubuntu version to 18.04 and I get another error. I found that the download link for augustus is no longer available (http://bioinf.uni-greifswald.de/augustus/binaries/augustus-3.3.3.tar.gz). I replaced it with GitHub link (https://github.com/Gaius-Augustus/Augustus/releases/download/v3.3.3/augustus-3.3.3.tar.gz) and it's worked.

So I propose this new recipe for busco 4.0.4.
[Singularity.busco-4.0.4.txt](https://github.com/SouthGreenPlatform/CulebrONT_pipeline/files/5835944/Singularity.busco-4.0.4.txt)

Regards,
Xavier

**Comment by julieaorjuela** [comment]
Thanks @X-Mialhe busco singularity is now available on 4.1.4 version.
