### ISSUE TITLE
culebrONT can't find SLURM

### ISSUE THREAD

**Issue by bbyrns** [SouthGreenPlatform/CulebrONT#5]
Hello,
Attempting to run the command 'culebrONT install_cluster -s slurm -e modules' in our HPC environment results in 'Error: Slurm was not found on your system !!'  despite the presence of a SLURM environment.  How does culebrONT check for SLURM?
Thanks

**Comment by sravel** [comment]
Hello, 
The command `culebrONT install_cluster -s slurm -e modules` check slurm with `sinfo`
https://slurm.schedmd.com/sinfo.html
then we try to select default queue with star with command ` sinfo -s | grep "*" | cut -d"*" -f1 `
can you send me the return of `sinfo -s`

thanks

**Comment by bbyrns** [comment]
Ah, I see, we have no default queue/partition enabled.  Is there any workaround for clusters without a default partition?
Thanks,
Brook

**Comment by julieaorjuela** [comment]
hello @bbyrns 
We can adapt regular expression, can you please give us output of command line sinfo -s please?

**Comment by sravel** [comment]
Is it still relevant or can I close the issue?
