### ISSUE TITLE
Error in rule run_flagstats_stats

### ISSUE THREAD

**Issue by serbier** [SouthGreenPlatform/CulebrONT#8]
Hi I'm trying to run test files and in rule run_flagstats_stats I get this error

Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job                    count    min threads    max threads
-------------------  -------  -------------  -------------
final                      1              1              1
rule_graph                 1              1              1
run_busco_version          1              1              1
run_flagstats_stats        1              1              1
run_report                 1              1              1
total                      5              1              1

Select jobs to execute...

[Sun Mar 27 13:58:47 2022]
Job 19: 
        making dag ...
        snakemake -s /home/scruz/miniconda3/envs/denovoAssembly/lib/python3.7/site-packages/culebrONT/snakefiles/Snakefile --use-singularity   --rulegraph --configfile /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_Output/config_corrected.yaml > /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_Output/FINAL_REPORT/dag.tmp
        dot -Tpng /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_Output/FINAL_REPORT/dag.tmp > /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_Output/FINAL_REPORT/dag.png
        

        (snakemake -s /home/scruz/miniconda3/envs/denovoAssembly/lib/python3.7/site-packages/culebrONT/snakefiles/Snakefile --use-singularity   --rulegraph --configfile /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_Output/config_corrected.yaml > /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_Output/FINAL_REPORT/dag.tmp
        dot -Tpng /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_Output/FINAL_REPORT/dag.tmp > /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_Output/FINAL_REPORT/dag.png) 1>/bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_Output/LOGS/Graph.o 2>/bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_Output/LOGS/Graph.e
        
[Sun Mar 27 13:58:50 2022]
Finished job 19.
1 of 5 steps (20%) done
Select jobs to execute...

[Sun Mar 27 13:58:50 2022]
Job 50: 
        make stats from flagstats
        

/home/scruz/miniconda3/envs/denovoAssembly/bin/python3 /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_Output/.snakemake/scripts/tmp01ffzrmc.get_stats_flagstats.py
[Sun Mar 27 13:58:52 2022]
Error in rule run_flagstats_stats:
    jobid: 50
    output: /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_Output/5percentB1-1/REPORT/5percentB1-1_flagstats.csv
    log: /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_Output/LOGS/run_flagstats_stats/5percentB1-1.o, /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_Output/LOGS/run_flagstats_stats/5percentB1-1.e (check log file(s) for error message)
Logfile /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_Output/LOGS/run_flagstats_stats/5percentB1-1.o not found.
Logfile /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_Output/LOGS/run_flagstats_stats/5percentB1-1.e not found.

RuleException:
CalledProcessError in line 244 of /home/scruz/miniconda3/envs/denovoAssembly/lib/python3.7/site-packages/culebrONT/snakefiles/Snakefile:
Command 'set -euo pipefail;  /home/scruz/miniconda3/envs/denovoAssembly/bin/python3 /bioinfo1/projects/bean/MinIon/software/Test_culebrONT/culebrONT_Output/.snakemake/scripts/tmp01ffzrmc.get_stats_flagstats.py' returned non-zero exit status 1.
  File "/home/scruz/miniconda3/envs/denovoAssembly/lib/python3.7/site-packages/culebrONT/snakefiles/Snakefile", line 244, in __rule_run_flagstats_stats
  File "/home/scruz/miniconda3/envs/denovoAssembly/lib/python3.7/concurrent/futures/thread.py", line 57, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: ../.snakemake/log/2022-03-27T135845.792157.snakemake.log

According to [this](https://stackoverflow.com/questions/44616073/thread-py-error-snakemake) when an error in thread.py occurs with snakemake could be related with an error in shell command than thread.py itself how could I debug the rule to know where is the error ? 

Thanks in advance

**Comment by sravel** [comment]
Hello we fix some bug of logging on the last release, can you try again with latest version? thanks
